baseurl = "https://example.org/"
languageCode = "en-us"
title = "Le Clown et la Fée"
theme = "hugo-strata-theme"

# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Describe your website"
  siteTedua = "http://association-tedua.fr"
	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = ['js/targetblank.js']
	custom_css  = []

	phrase_fin = ""
	video_id = ""


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Le clown et la fée**<br> est un spectacle pour les enfants<br> et leurs parents,<br> à la fois!"
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		gitlab = ""
		dribbble = ""
		facebook = "groups/386241745191819/"
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; John Doe",
			"Design: [HTML5 UP](//html5up.net)",
			"Photos et vidéo: [RGB FOX](https://www.facebook.com/profile.php?id=100011568698447)"
		]


	[params.about]
		hide  = false
		title = " « Quelle est la couleur du ciel, s'il vous plaît? » "
		content = "En errance, un clown triste apparait : il a perdu ses couleurs. Une fois sur scène, il se retrouve devant son public. Il s'explique, il n'a plus et ne se souvient même plus des couleurs. « Messieurs-dames les enfants et autres Papamamans » vont l'aider à appeler Madame la fée : « **car si nous sommes, nous pouvons.** » <br>Cette dernière ne lui donne pas le choix : pour qu’il puisse parcourir ses rêves et retrouver ses couleurs, il devra s’endormir et affronter ses peurs. Des voyages initiatiques au travers desquels, il devra apprendre et réapprendre le rythme, l’équilibre, l’écoute et le partage. <br>Ainsi, couleurs après couleurs il récupérera sa joie de vivre et continuera sa route…<br><br>"


	[params.portfolio]
		hide  = false
		title = "Images et Histoire"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Les premiers instants."
			description = "note de l'auteur : Offrir à l'observation du public, un contre pied, comme une invitation à voir la vie plus large que la joie qu'un clown offre spontanément et créer l'intrigue de la redécouverte de cette joie."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "L'appel à l'aide."
			description = "Note de l'auteur : À la fin du monologue d'entrée, le clown lance l'appel à l'aide, déjà aidé par les enfants, ainsi faire connecter cette acte simple pour les enfants : de s'en remettre à l'autre. Celui que nous oublions à force de se penser plus important qu'autrui."

	  [[params.portfolio.gallery]]
				image = "fulls/l'appel2.jpg"
				thumb = "thumbs/l'appel.jpg"
				title = "L'arrivée."
				description = "Note de l'auteur : Il y aura toujours bien un autre. Certainement même, un autre qui était déjà là depuis le début. Il n'a toujours suffit qu'un peu d'aveu pour rendre possible l'invisible."

		[[params.portfolio.gallery]]
			image = "fulls/explication 2.jpg"
			thumb = "thumbs/explication.jpg"
			title = "L'outillage à vivre."
			description = "Note de l'auteur : De la même manière qu'on attrape un enfant dans une bêtise qu'il doit bien savoir quelque part comme bêtise. L'être détaché du monde, tel qu'est une fée dans le monde du clown, ne peut pas faire autrement que de nommé fort, en y mettant du punch."

		[[params.portfolio.gallery]]
			image = "fulls/premier rêve2.jpg"
			thumb = "thumbs/premier rêve.jpg"
			title = "Premier rêve."
			description = "Que sont les rêves si ce n'est la certitude de l'illusion active. Proposer un environement où tout est illusion, où tout est rêve, n'est ce pas le bon moyen pour voir les choses avec recul. par exemple : qu'est ce qu'un objet?"

		[[params.portfolio.gallery]]
			image = "fulls/livrer l'expression2.jpg"
			thumb = "thumbs/livrer l'expression.jpg"
			title = "Livrer l'expression."
			description = "Une des grandes oeuvres de la vie est de faire surgir l'expression. c'est peut être pour cela que le théâtre a traversé les âges. Qu'avons-nous donc à faire pour que cela se produise? Peut être que l'expression n'est pas à faire, peut être que cela ne fait que se recevoir."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Informations pratiques"

	[params.contact]
		hide  = false
		title = "Pour nous contacter,"
		content = "Plusieurs options s'offrent à vous ici, vous pouvez directement écrire ici, ou suivre le lien de l'adresse mail. mais aussi nous appeler ou nous envoyé un courrier."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "44.9065, -0.5761"
		address = [
			"22 rue Leydet",
			"Apt n°9",
			"33800 BORDEAUX"
		]
		phone = "06-51-60-97-04"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "diffusion@association-tedua.fr"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Votre nom"
			email = "Votre email"
			message = "Message"
			submit = "Envoyez"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Page d'accueil"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Informations pratiques"
	url  = "post/"
	weight = 0
